# Generated by Django 3.2.6 on 2021-08-09 23:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Enter you article text here.', max_length=2000),
        ),
    ]
